[package]
name = "builtin"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
petgraph = "0.7.1"
rustworkx-core = "0.16.0"
serde = "1.0.217"
serde_json = "1.0.138"
rand = "0.8"
solver = { path = "../solver" }

